### ISSUE TITLE
怎么给input  赋value

### ISSUE THREAD

**Issue by mayue100** [aralejs/autocomplete#113]
seajs.use(['autocomplete'], function(AutoComplete) {
        var ac = new AutoComplete({
            trigger: '#gszgswjg',
            //header: '<div class="{{classPrefix}}-header">筛选省市：</div>',
            //footer: '<div class="{{classPrefix}}-footer">搜索 {{query}} 的{{length}}个结果</div>',
            //html: '<strong>{{city}}</strong><span>{{prov}}</span>',
            ubmitOnEnter: false,
            dataSource: [
              {label: '上海', value: 'shanghai',target:'sh'},
              {label: '苏州', value: 'suzhou'},
              {label: '深圳', value: 'shenzhen'},
              {label: '沈阳', value: 'shenyang'}
            ],
        width: 268
    }).render();

```
ac.element.on('click', function(e) {

})
```

});

**Comment by mayue100** [comment]
谢谢

**Comment by afc163** [comment]
跨度两年的交流。
